services:
  web_username:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: redis:alpine
  db:
    image: mariadb:10-focal
    environment:
      MYSQL_ROOT_PASSWORD: password456
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user1
      MYSQL_PASSWORD: password123
